### ISSUE TITLE
You may need to add PYTHONIOENCODING=utf-8 to your environment

### ISSUE THREAD

**Issue by TheNopePlant** [anatolykopyl/youtube-cdl#1]
Received after agreeing yes to all the channels that i want to download

`Traceback (most recent call last):`
`  File "main.py", line 83, in <module>`
`    c.print('All done! \U0001f389')`
`  File "/home/pi/.local/lib/python3.7/site-packages/rich/console.py", line 1506, in print`
`    self._buffer.extend(new_segments)`
`  File "/home/pi/.local/lib/python3.7/site-packages/rich/console.py", line 776, in __exit__`
`    self._exit_buffer()`
`  File "/home/pi/.local/lib/python3.7/site-packages/rich/console.py", line 735, in _exit_buffer`
`    self._check_buffer()`
`  File "/home/pi/.local/lib/python3.7/site-packages/rich/console.py", line 1697, in _check_buffer`
`    self.file.write(text)`
`UnicodeEncodeError: 'latin-1' codec can't encode character '\U0001f389' in position 10: ordinal not in range(256)`
`*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***`

**Comment by TheNopePlant** [comment]
Fixed by changing line 83 from 
`c.print('All done! 🎉')`

to
`c.print('All done!')`

**Comment by anatolykopyl** [comment]
Thanks for the report! Though I don't plan on removing Unicode since it's recommended that you have it enabled by default.
