### ISSUE TITLE
Ability to mark downloaded videos if resulting files have been moved

### ISSUE THREAD

**Issue by TheNopePlant** [anatolykopyl/youtube-cdl#3]
Hi There,

I was wondering if it would be possible when a channel is set to download, a log file is created that contains a list of all the videos on that channel. 

When a video is downloaded, the resulting log file is marked with a flag that states whether the video has already been downloaded. Thus is the drive you are downloading to fills up and the resulting files are moved to a different location, it is possible to know what has already been downloaded.

At the start of the main.py script, all video names are downloaded and updated in the list. This would allow for the fetching of new videos. It would also require the existing videos in said list to not have their downloaded status flag altered.

Hopefully my explanation makes sense.

Cheers

**Comment by anatolykopyl** [comment]
Youtube-dl has an argument for this and you can pass it through via `--download_archive`. 

> Download only videos not listed in the archive file. Record the IDs of all downloaded videos in it.

[Youtube-dl README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#video-selection)

For example: 
```
python main.py --download_archive done.txt
```
